/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package APITesting;

import org.junit.Test;
import static org.junit.Assert.*;
import static io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import static org.hamcrest.Matchers.*;

public class AppTest {
    @Test
    public void assertResponseValue() {
       get("https://jsonplaceholder.typicode.com/posts/1").then().statusCode(200).assertThat()
          .body("id", equalTo(1)); 
    }
}
